//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  module: Module;
  moduleConnection: ModuleConnection;
  quiz: Quiz;
  quizConnection: QuizConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryModuleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryModuleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ModuleFilter>;
};


export type QueryQuizArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuizConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuizFilter>;
};

export type DocumentFilter = {
  module?: InputMaybe<ModuleFilter>;
  quiz?: InputMaybe<QuizFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Module | Quiz | Folder;

export type ModuleSlides = {
  __typename?: 'ModuleSlides';
  title: Scalars['String']['output'];
  layout?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  instructorNotes?: Maybe<Scalars['String']['output']>;
};

export type Module = Node & Document & {
  __typename?: 'Module';
  title: Scalars['String']['output'];
  moduleNumber: Scalars['Float']['output'];
  slug: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  slides?: Maybe<Array<Maybe<ModuleSlides>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ModuleSlidesFilter = {
  title?: InputMaybe<StringFilter>;
  layout?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  instructorNotes?: InputMaybe<StringFilter>;
};

export type ModuleFilter = {
  title?: InputMaybe<StringFilter>;
  moduleNumber?: InputMaybe<NumberFilter>;
  slug?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  slides?: InputMaybe<ModuleSlidesFilter>;
};

export type ModuleConnectionEdges = {
  __typename?: 'ModuleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Module>;
};

export type ModuleConnection = Connection & {
  __typename?: 'ModuleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ModuleConnectionEdges>>>;
};

export type QuizQuestionsOptions = {
  __typename?: 'QuizQuestionsOptions';
  text?: Maybe<Scalars['String']['output']>;
  isCorrect?: Maybe<Scalars['Boolean']['output']>;
};

export type QuizQuestions = {
  __typename?: 'QuizQuestions';
  question: Scalars['String']['output'];
  type?: Maybe<Scalars['String']['output']>;
  options?: Maybe<Array<Maybe<QuizQuestionsOptions>>>;
  explanation?: Maybe<Scalars['String']['output']>;
};

export type Quiz = Node & Document & {
  __typename?: 'Quiz';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  passingScore?: Maybe<Scalars['Float']['output']>;
  questions?: Maybe<Array<Maybe<QuizQuestions>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type QuizQuestionsOptionsFilter = {
  text?: InputMaybe<StringFilter>;
  isCorrect?: InputMaybe<BooleanFilter>;
};

export type QuizQuestionsFilter = {
  question?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  options?: InputMaybe<QuizQuestionsOptionsFilter>;
  explanation?: InputMaybe<StringFilter>;
};

export type QuizFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  passingScore?: InputMaybe<NumberFilter>;
  questions?: InputMaybe<QuizQuestionsFilter>;
};

export type QuizConnectionEdges = {
  __typename?: 'QuizConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Quiz>;
};

export type QuizConnection = Connection & {
  __typename?: 'QuizConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<QuizConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateModule: Module;
  createModule: Module;
  updateQuiz: Quiz;
  createQuiz: Quiz;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateModuleArgs = {
  relativePath: Scalars['String']['input'];
  params: ModuleMutation;
};


export type MutationCreateModuleArgs = {
  relativePath: Scalars['String']['input'];
  params: ModuleMutation;
};


export type MutationUpdateQuizArgs = {
  relativePath: Scalars['String']['input'];
  params: QuizMutation;
};


export type MutationCreateQuizArgs = {
  relativePath: Scalars['String']['input'];
  params: QuizMutation;
};

export type DocumentUpdateMutation = {
  module?: InputMaybe<ModuleMutation>;
  quiz?: InputMaybe<QuizMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  module?: InputMaybe<ModuleMutation>;
  quiz?: InputMaybe<QuizMutation>;
};

export type ModuleSlidesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  layout?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  instructorNotes?: InputMaybe<Scalars['String']['input']>;
};

export type ModuleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  moduleNumber?: InputMaybe<Scalars['Float']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  slides?: InputMaybe<Array<InputMaybe<ModuleSlidesMutation>>>;
};

export type QuizQuestionsOptionsMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  isCorrect?: InputMaybe<Scalars['Boolean']['input']>;
};

export type QuizQuestionsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  options?: InputMaybe<Array<InputMaybe<QuizQuestionsOptionsMutation>>>;
  explanation?: InputMaybe<Scalars['String']['input']>;
};

export type QuizMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  passingScore?: InputMaybe<Scalars['Float']['input']>;
  questions?: InputMaybe<Array<InputMaybe<QuizQuestionsMutation>>>;
};

export type ModulePartsFragment = { __typename: 'Module', title: string, moduleNumber: number, slug: string, description?: string | null, duration?: string | null, slides?: Array<{ __typename: 'ModuleSlides', title: string, layout?: string | null, content?: any | null, image?: string | null, videoUrl?: string | null, instructorNotes?: string | null } | null> | null };

export type QuizPartsFragment = { __typename: 'Quiz', title: string, slug: string, passingScore?: number | null, questions?: Array<{ __typename: 'QuizQuestions', question: string, type?: string | null, explanation?: string | null, options?: Array<{ __typename: 'QuizQuestionsOptions', text?: string | null, isCorrect?: boolean | null } | null> | null } | null> | null };

export type ModuleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ModuleQuery = { __typename?: 'Query', module: { __typename: 'Module', id: string, title: string, moduleNumber: number, slug: string, description?: string | null, duration?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, slides?: Array<{ __typename: 'ModuleSlides', title: string, layout?: string | null, content?: any | null, image?: string | null, videoUrl?: string | null, instructorNotes?: string | null } | null> | null } };

export type ModuleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ModuleFilter>;
}>;


export type ModuleConnectionQuery = { __typename?: 'Query', moduleConnection: { __typename?: 'ModuleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ModuleConnectionEdges', cursor: string, node?: { __typename: 'Module', id: string, title: string, moduleNumber: number, slug: string, description?: string | null, duration?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, slides?: Array<{ __typename: 'ModuleSlides', title: string, layout?: string | null, content?: any | null, image?: string | null, videoUrl?: string | null, instructorNotes?: string | null } | null> | null } | null } | null> | null } };

export type QuizQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type QuizQuery = { __typename?: 'Query', quiz: { __typename: 'Quiz', id: string, title: string, slug: string, passingScore?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, questions?: Array<{ __typename: 'QuizQuestions', question: string, type?: string | null, explanation?: string | null, options?: Array<{ __typename: 'QuizQuestionsOptions', text?: string | null, isCorrect?: boolean | null } | null> | null } | null> | null } };

export type QuizConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuizFilter>;
}>;


export type QuizConnectionQuery = { __typename?: 'Query', quizConnection: { __typename?: 'QuizConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'QuizConnectionEdges', cursor: string, node?: { __typename: 'Quiz', id: string, title: string, slug: string, passingScore?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, questions?: Array<{ __typename: 'QuizQuestions', question: string, type?: string | null, explanation?: string | null, options?: Array<{ __typename: 'QuizQuestionsOptions', text?: string | null, isCorrect?: boolean | null } | null> | null } | null> | null } | null } | null> | null } };

export const ModulePartsFragmentDoc = gql`
    fragment ModuleParts on Module {
  __typename
  title
  moduleNumber
  slug
  description
  duration
  slides {
    __typename
    title
    layout
    content
    image
    videoUrl
    instructorNotes
  }
}
    `;
export const QuizPartsFragmentDoc = gql`
    fragment QuizParts on Quiz {
  __typename
  title
  slug
  passingScore
  questions {
    __typename
    question
    type
    options {
      __typename
      text
      isCorrect
    }
    explanation
  }
}
    `;
export const ModuleDocument = gql`
    query module($relativePath: String!) {
  module(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ModuleParts
  }
}
    ${ModulePartsFragmentDoc}`;
export const ModuleConnectionDocument = gql`
    query moduleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ModuleFilter) {
  moduleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ModuleParts
      }
    }
  }
}
    ${ModulePartsFragmentDoc}`;
export const QuizDocument = gql`
    query quiz($relativePath: String!) {
  quiz(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...QuizParts
  }
}
    ${QuizPartsFragmentDoc}`;
export const QuizConnectionDocument = gql`
    query quizConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: QuizFilter) {
  quizConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...QuizParts
      }
    }
  }
}
    ${QuizPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      module(variables: ModuleQueryVariables, options?: C): Promise<{data: ModuleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModuleQueryVariables, query: string}> {
        return requester<{data: ModuleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModuleQueryVariables, query: string}, ModuleQueryVariables>(ModuleDocument, variables, options);
      },
    moduleConnection(variables?: ModuleConnectionQueryVariables, options?: C): Promise<{data: ModuleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModuleConnectionQueryVariables, query: string}> {
        return requester<{data: ModuleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModuleConnectionQueryVariables, query: string}, ModuleConnectionQueryVariables>(ModuleConnectionDocument, variables, options);
      },
    quiz(variables: QuizQueryVariables, options?: C): Promise<{data: QuizQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizQueryVariables, query: string}> {
        return requester<{data: QuizQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizQueryVariables, query: string}, QuizQueryVariables>(QuizDocument, variables, options);
      },
    quizConnection(variables?: QuizConnectionQueryVariables, options?: C): Promise<{data: QuizConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizConnectionQueryVariables, query: string}> {
        return requester<{data: QuizConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizConnectionQueryVariables, query: string}, QuizConnectionQueryVariables>(QuizConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  